# Generated by Django 4.1.5 on 2023-02-09 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_image_alter_profile_profile_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('metaTitle', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cover_img', models.ImageField(upload_to='images/')),
                ('default_privacy', models.IntegerField(default=0)),
                ('is_liked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_journals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
