# Generated by Django 4.1.5 on 2023-02-12 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_journal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=2000)),
                ('location', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('entry_privacy', models.IntegerField(default=0)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='image_entries', to='core.image')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='journal_entries', to='core.journal')),
            ],
        ),
    ]
