# Generated by Django 4.1.5 on 2023-02-13 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_entry_image_alter_image_image_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parrent',
            new_name='parent',
        ),
        migrations.AlterField(
            model_name='comment',
            name='entry',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_comments', to='core.entry'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='journal',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_comments', to='core.journal'),
        ),
    ]
