# Generated by Django 4.1.5 on 2023-02-13 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_parrent_comment_parent_alter_comment_entry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_comments', to='core.entry'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_comments', to='core.journal'),
        ),
    ]
