# Generated by Django 4.1.5 on 2023-02-13 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_likes', to='core.image'),
        ),
        migrations.AlterField(
            model_name='like',
            name='entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_likes', to='core.entry'),
        ),
    ]
