# Generated by Django 4.1.5 on 2023-02-15 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_comment_is_archived_entry_is_archived_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('album', models.CharField(max_length=200)),
                ('Journal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_song', to='core.entry')),
                ('entry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_song', to='core.entry')),
            ],
        ),
    ]
