# Generated by Django 4.1.5 on 2023-02-15 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
