# Generated by Django 4.1.5 on 2023-02-16 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_song_is_archived'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='Journal',
            new_name='journal',
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=200)),
                ('is_archived', models.BooleanField(default=False)),
                ('entry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_videos', to='core.entry')),
                ('journal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_videos', to='core.entry')),
            ],
        ),
    ]
