# Generated by Django 4.1.5 on 2023-02-16 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_location', to='core.entry'),
        ),
        migrations.AddField(
            model_name='place',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='place',
            name='journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_location', to='core.journal'),
        ),
        migrations.AddField(
            model_name='place',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_location', to='core.profile'),
        ),
        migrations.AlterField(
            model_name='song',
            name='journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_song', to='core.journal'),
        ),
        migrations.AlterField(
            model_name='video',
            name='journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_videos', to='core.journal'),
        ),
    ]
