# Generated by Django 4.1.5 on 2023-02-17 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_place_entry_place_is_archived_place_journal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='location',
        ),
        migrations.AddField(
            model_name='place',
            name='latitude',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='place',
            name='longitude',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
