# Generated by Django 4.1.5 on 2023-02-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_place_location_place_latitude_place_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.CharField(default='0', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.CharField(default='0', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
