# Generated by Django 4.1.5 on 2023-02-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_place_latitude_alter_place_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='images/blank-profile-picture.png', upload_to='images/'),
        ),
    ]
