# Generated by Django 4.1.5 on 2023-02-18 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 18, 16, 25, 13, 487298)),
        ),
    ]
