# Generated by Django 4.1.5 on 2023-02-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_journal_cover_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_album',
            field=models.BooleanField(default=False),
        ),
    ]
